#!/usr/bin/env bash

source "./locale"

export IFS=" "
add_param "server_host" "Host of the target server"
add_param "server_port" "Port of the target server"
add_param "proxy_host" "Host of the external proxy"
add_param "proxy_metaport" "Port of the external proxy used for metadata"
add_param "proxy_dataport" "Port of the external proxy used for data lines"
parse_opts $@

#Set trap for shutdown
trap 'exit_kill' SIGTERM SIGINT SIGABRT

#Initiate sockets
connect_coproc "Connecting to proxy meta at" "TCP" "$proxy_host:$proxy_metaport" "" ln_pi ln_po

while true; do
	#Wait for connections
	read -r -u $ln_pi -t 0.1 s_addr
	s_code=$?
	if [[ $s_code -eq 0 ]]; then
		v_echo "Connecting a client $s_addr"
		{
			#Set trap for shutdown
			trap 'exit_kill' SIGTERM SIGINT SIGABRT
			
			#Initiate sockets
			connect_coproc "[$$] Connecting to server at" "TCP" "$server_host:$server_port" "" ln_si ln_so
			connect_coproc "[$$] Connecting to proxy at" "TCP" "$proxy_host:$proxy_dataport" "" ln_ci ln_co

			#Send address to proxy
			cat >&$ln_co <&0
			
			#Exchange data
			cat <&$ln_si >&$ln_co &
			cat >&$ln_so <&$ln_ci &
			exit_wait_killing
		} <<<"$s_addr" &
	elif [[ $s_code -eq 1 ]]; then
		v_echo "Proxy disconnected, exiting"
		exit_kill
	fi
done
